# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'happyshop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for happyshop
    pod 'Alamofire', '~> 3.5.0'
    pod 'ObjectMapper', '~> 1.3.0'
    pod 'AlamofireObjectMapper', '~> 3.0.2'
    pod 'Swinject', '~> 1.1.0'
end
